export const UNIDADES_MEDIDA = [
  { value: "UN", label: "UN" },
  { value: "PÇ", label: "PÇ" },
  { value: "KG", label: "KG" },
  { value: "G", label: "G" },
  { value: "TON", label: "TON" },
  { value: "L", label: "L" },
  { value: "ML", label: "ML" },
  { value: "M", label: "M" },
  { value: "M2", label: "M2" },
  { value: "M3", label: "M3" },
  { value: "CX", label: "CX" },
  { value: "PCT", label: "PCT" },
  { value: "SC", label: "SC" },
  { value: "PR", label: "PR" },
  { value: "CJ", label: "CJ" },
] as const

export const UNIDADE_LABEL: Record<string, string> = {
  UN: "UN",
  "PÇ": "PÇ",
  KG: "KG",
  G: "G",
  TON: "TON",
  L: "L",
  ML: "ML",
  M: "M",
  M2: "M2",
  M3: "M3",
  CX: "CX",
  PCT: "PCT",
  SC: "SC",
  PR: "PR",
  CJ: "CJ",
}

export const MONTHS = [
  { value: "0", label: "Janeiro" },
  { value: "1", label: "Fevereiro" },
  { value: "2", label: "Marco" },
  { value: "3", label: "Abril" },
  { value: "4", label: "Maio" },
  { value: "5", label: "Junho" },
  { value: "6", label: "Julho" },
  { value: "7", label: "Agosto" },
  { value: "8", label: "Setembro" },
  { value: "9", label: "Outubro" },
  { value: "10", label: "Novembro" },
  { value: "11", label: "Dezembro" },
]
